#Site settings
name : Curriculum Vitae
description : Website for Thomas S. Nielsen
baseurl: ""
url : "http://localhost:4000"
paginate : 5
markdown : rdiscount
permalink : pretty
highlighter : pygments